name: porest-server dev ci

on:
  push:
    branches: [ 'dev' ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Setup node.js 18.12.1
        uses: actions/setup-node@v3
        with: 
          node-version: 18.12.1
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm run test
